Creating CheckerGames. also methods to validate if a move is a valid …
mcc-sw-eng-course/python-programs-charlieitesm pull request #31
Opened 2019-04-09 06:29 UTC by maximussage1

…move.

2019-04-09 06:29 UTC, maximussage1 commented
Please don't merge, just review.

2019-04-09 16:37 UTC, charlieitesm commented on src/L8/game/checkers/checkers_constans.py
> +class CheckerColors(Enum):
In English Checkers, all pieces must only use the Black squares, nobody is allowed to jump horizontally or vertically, only diagonally (even when capturing pieces).
Knowing this, we can validate, not based on the color on the board, but the direction of the movement. So I think we could do without this Enum.

2019-04-09 16:37 UTC, charlieitesm commented on src/L8/game/checkers/checkers_game.py
> +        move = CheckersMove(r1, c1, r2, c2, is_jump)
How are you reading the origin of the piece that is to be moved? I believe that the current engine is not supporting reading the origin. I was thinking that we might want to adapt some of the older methods in the engine for that purpose.

2019-04-09 16:37 UTC, charlieitesm commented on src/L8/game/checkers/checkers_game.py
> +        r1, c1, r2, c2, is_jump, player_color = move[MOVE]
The color of the player can be determined by the GameToken he is holding, how are you reading the player_color?

2019-04-09 16:37 UTC, charlieitesm commented on src/L8/game/checkers/checkers_utils.py
> +        legal_moves = CheckerGameUtil.get_valid_moves_for_player(board, player_color)
What's the cost of calculating the whole solution space (even for moves that the player is not currently making)? Wouldn't it be better if we calculate if the current move is valid?

2019-04-10 23:53 UTC, charlieitesm requested changes
Just a minor thing there with typing for the player's game token, otherwise it looks pretty solid!

2019-04-10 23:53 UTC, charlieitesm commented on src/L8/game/checkers/checkers_game.py
> +            player_color = player.game_token
Here you are storing player_color with a GameToken object, but on lines 19 and 21 you are storing a str in the same variable.

I would recommend that on lines 19 and 21 you get the actual singleton GameToken object. I believe there is a util method that can fetch you a GameToken instance given a str representation of said token, if there is not a method, we could add it.

By not keeping the typing consistent, you might run into issues if you are using if's to compare values, after all, a str object will not evaluate to True against a GameToken object (unless you transform either to the other value).

2019-04-11 15:24 UTC, merged

2019-04-11 15:25 UTC, charlieitesm commented
I merged this changes @maximussage1 so that we can continue iterating on it. We can address changes on a following PR, in the meantime I'll move continue adding the Factory and the parameters